### PR TITLE
Combine PRs #25, #26, #27, #28 and bump release to 1.2.4

### PR DESCRIPTION
**Pull request by jimklimov**
This PR represents the internal build we plan to use. It combines features added or fixed by earlier feature-based PRs:
* #25
* #26 
* #27 
* #28

...including resolution of conflicts, since many of them touch same lines, and adding some synergy (exception class include in two ways building on top of PR #26; using the exception when handling HTTPS arguments).

It is recommended to merge this PR (and hopefully score the earlier four automatically) in one simple swoop :)

### CODE REVIEW

**Review by thinksabin — APPROVED** [review]
thanks

**Review by thinksabin — APPROVED** [review]
thanks

**Comment by jimklimov** [comment]
Thanks for the merge! Some more extensions are brewing; not sure I want to tediously separate them by subject however :)

**Comment by thinksabin** [comment]
no worries :)

**Pull request merged**
